### ISSUE TITLE
Is a question?

### ISSUE THREAD

**Issue by NicolasYL** [ckormanyos/wide-integer#1]
uint128_t n("12312452345");
	std::cout << std::boolalpha;
	std::cout << std::is_integral<uint128_t>::value << '\n';

output : false

**Comment by johnmcfarlane** [comment]
You would think that this was `true` given it is meant to apply to "[any implementation-defined extended integer types](https://en.cppreference.com/w/cpp/types/is_integral)". I'm 99% certain 128-bit integers fall into this category given [the definition of extended integer types](http://eel.is/c++draft/basic.fundamental#1). But for whatever reason that are not seen that way by popular standard libraries.

Note that I've [chosen differently](https://github.com/johnmcfarlane/cnl/blob/develop/include/cnl/_impl/type_traits/is_integral.h#L22) in the CNL library which reimplements many numerics-related standard headers including `<cstdint>`.

**Comment by ckormanyos** [comment]
Yes. It seems like it should be true. I can start looking into this. Does anyone know if there really should be support in namespace std for the UDT? Or in another namespace?

**Comment by johnmcfarlane** [comment]
Users are not permitted to specialize `std::is_integral`.

**Comment by ckormanyos** [comment]
I've always been confused by this kind of thing. How can std::is_integral<UDT>::value be true if we are not allowed to make a template specialization in namespace std?

**Comment by johnmcfarlane** [comment]
We aren't but standard library implementors are allowed.

**Comment by ckormanyos** [comment]
> We aren't but standard library implementors are allowed.

OK. So I'll put the relevant templates within the UDT's namespace, similar to in CNL.
Thanks. This will be in the next update.

**Comment by johnmcfarlane** [comment]
I just realized what you mean by `uint128_t`. It's the common alias for built-in type, `unsigned __int128` which is what I thought was being discussed. I realize that you're using it as an alias to instantiations of your class template.

Given that, a couple of things.

Firstly, I would think twice about using this name -- not only because it's already found in common tool-chains (namely GCC and Clang) -- but because all the identifiers with names `[u]intN_t` are aliases to built-in types and never class types. This may confuse anyone who is aware of existing `int128_t`-like aliases and expects a language-level type.

The wide integer WG21 paper, [P0539](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0539r4.html) even mentions how LEWG asked the author to drop their own aliases:

> Non template aliases for integers of particular width (for example int128_t) are handled in separate paper P0102R0. There was an implicit request from LEWG to remove those aliases from this paper, as they were rising a lot of questions on some platforms.

However, I acknowledge that it is used the way you're using it by Boost.Multiprecision so it's not a huge deal. However,

Secondly, I'd be even less inclined to redefine `is_integral` within your namespace in order to make your `int128_t` pass. `is_integral` really is intended to refer to native types. Again, it's in your `wide_integer` namespace and there's a case for saying that it's an integer. (I mean, it really is an integer!) However, that's not necessarily what readers will expect when they perform this test.

Additionally, there's a `std` class template which you *are* allowed to specialize for your own types, `std::numeric_limits` which has an `is_integer` member. It's totally fine to create your own partial specialization of `std::numeric_limits` and fill it out with all the members that the library-provided specializations have. It's a little more work but I think it's the least problematic direction.

Again, apologies for not paying closer attention to the question and your library (which is coming along nicely by the way)!

**Comment by ckormanyos** [comment]
These are really good points. Thank you very much for elaborating, John.
I have, in fact, pushed support for the namespace-local implementations of is_integral.

Yes, there is already support for std::numeric_limits<UDT> for this class.

Based on your inputs, I am, in fact, wondering about names of the kind (u)int_128_t, 256, etc.
For the moment, they remain in use. It will, however, be interesting to see how LEWG
progresses in this area.

Kind regards, Chris

**Comment by ckormanyos** [comment]
is_integer has been implemented in the specific namespace of the uintwide_t class.

**Comment by johnmcfarlane** [comment]
Of relevance, [Is __int128 integral? A survey](https://quuxplusone.github.io/blog/2019/02/28/is-int128-integral/) by @Quuxplusone

**Comment by ckormanyos** [comment]
Thanks @johnmcfarlane. Nice report. I still follow and appreciate your great and awesome work in [CNL](https://github.com/johnmcfarlane/cnl)
