### ISSUE TITLE
 Split tests into many individual tests each with `main()`

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#131]
From #130 we find out that, the tests aren't very easy to use.

There is one single huge result in a single program.

The purpose of this issue is to attempt to find a sensible way to split `wide-integer`'s tests into many individual tests with each having independent `main()` functions thereby allowing for their running in parallel

**Comment by johnmcfarlane** [comment]
Suggestion:
* Start by breaking up the target, _test_uintwide_t_, in test/unit/_impl/wide-integer.cpp each one target per source file.
* Invoke the tests with `ctest --output-on-failure --parallel 8` to run 8 at a time.
* Use `assert` to test each assumption: it prints a decent diagnostic message with very terse code.
* Or consider using a testing framework like Catch2 or GTest to generate the test cases so that you don't need to write a `main` function for each .cpp.
* When there are multiple assertions in a test, consider breaking into multiple tests within the same source file.

**Comment by ckormanyos** [comment]
> Start by breaking up the target, `test_uintwide_t`, ...

Indeed. That is sound advice @johnmcfarlane. My priority at the moment is that you can move forward, but i'll look into that as it rolls forward.

Thankis John!

**Comment by ckormanyos** [comment]
At the moment, with the runners on GHA, I'm happy with the testing. I'll close this issue but if anything changes, reconsider then.

Cc: @johnmcfarlane
