### ISSUE TITLE
Handle messages/warnings from clang-tidy

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#145]
The purpose of this issue is to track tidying up for clang-tidy. See also #143.

CMake builds with clang-tidy reveal numerous areas for modernization, performance, metrics violations, non-viable comparisons, etc.

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane I am starting to tidy up based on messages from `clang-tidy`.

I installed `clang-tidy`locally on Ubuntu.

Could you please kick start me on a command-line syntax to compile all the test-and-example files (or at least one of them) with the language guidelines you originaly set up [here](https://github.com/ckormanyos/wide-integer/blob/master/.clang-tidy)?

**Comment by johnmcfarlane** [comment]
Hi @ckormanyos. From an empty build directory:

```sh
cmake -DCMAKE_CXX_CLANG_TIDY=clang-tidy <path-to-project>
cmake --build . --parallel 8
```

**Comment by ckormanyos** [comment]
This is moving right along. The syntax improvements are being handled in the `clang_tidy_syntax_cleanup` branch.

So far, inclusion of `clang-tidy`'s guidelines `clang*`, `modernize*`, `cppcoreguidelines*`, `hicpp*`, `cert*`, `altera*`, `bugprone*`, `google*` has yielded sensible improvements.

Still need to include `readibility*` and `llvm*`.

@johnmcfarlane I will ask you for a review upon completion.

**Comment by johnmcfarlane** [comment]
Great! If you aren't too sure about any of the rules and, after some consideration, don't agree with them, don't be afraid to keep them excluded. Not everything applies to every project, some stuff is inappropriate, wrong or broken for a normal C++ project (llvmlib and Objective C stuff).

* [my list of CNL checks I probably will never enable](https://github.com/johnmcfarlane/cnl/blob/main/.clang-tidy#L4_L29)
* [my list of CNL checks I probably should fix](https://github.com/johnmcfarlane/cnl/blob/main/.clang-tidy#L30_L45)

Also, if you do address a diagnostic, do make sure you properly fix the problem; don't just make the warning go away. Otherwise, you've just made things worse. (It's better to know you've got a problem than to not know.)

For example, if there is a conversation/narrowing warning, don't just use `static_cast` to make it go away. Ask: "could I lose data here?"

**Comment by ckormanyos** [comment]
> Great! If you aren't too sure about any of the rules and, after some consideration, don't agree with them, don't be afraid to keep them excluded. Not everything applies to every project, some stuff is inappropriate, wrong or broken for a normal C++ project (llvmlib and Objective C stuff).

Indeed, John I agree. I was relatively new to `clang-tidy`, although I've dealt with plenty of syntax checking tools in numerous languages over the decades. I must say, i'm quite happy with `clang-tidy` with its informative and rich sets of guidelines.

I ended up checking with lines like this (basically everything activated with as few deactivations as made sense to me):

```sh
clang-tidy-12 examples/example000_numeric_limits.cpp --header-filter=uintwide_t -checks=*,-fuchsia-*,-llvmlibc-*,-llvm-header-guard,-readability-identifier-naming,-readabality-avoid-const-params-in-decls -- -I. -DWIDE_INTEGER_HAS_M
UL_8_BY_8_UNROLL > tidy.txt
```

Along the way, I was learning the disable syntax, so i still have a few completely blotted out lines with `// NOLINT`. I'll refine these in a final round.

CI is running green on my tidy branch. i'll repair a few things, then wrap up that activity.

Cc: @johnmcfarlane

**Comment by ckormanyos** [comment]
I ended up settling on the following rule set (with manual line-level suppressions for the few remaining warning messages)

``´sh
clang-tidy-12 examples/example000_numeric_limits.cpp --header-filter=uintwide_t -checks=*,-fuchsia-*,-llvmlibc-*,-llvm-header-guard,-readability-identifier-naming,-readability-avoid-const-params-in-decls,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-altera-struct-pack-align -- -I. -DWIDE_INTEGER_HAS_MUL_8_BY_8_UNROLL > tidy.txt
```

This was actually a good exercise. For the skeptical on syntax checkers, i believe i found about 10 code items that were really error-prone and at least two unfound, non-tested errors. The code for `operator+=()`, for instance, had an actual recursive-call bug, non-tested (test cases to be added).

**Comment by johnmcfarlane** [comment]
One thing I noticed: you haven't removed the exclusions from .clang-tidy. What happens if more of the checks fail in the future? How will you find out if they are not being checked in the workflow?

**Comment by ckormanyos** [comment]
> One thing I noticed: you haven't removed the exclusions from .clang-tidy. What happens if more of the checks fail in the future? How will you find out if they are not being checked in the workflow?

Establishing a reliable process for handling `clang-tidy` is tracked in #162.

The overall experience was great with this tool. In about 10k lines of code, both the tool as well as my code itself had about 5-10 bugs or near-bugs --- which is a very equitable tradeoff and very good for a syntax checker in my opinion. Considering the convenient licensing of `clang-tidy`, it really provides great benefit with low effort/cost.

Back to the process topic. I noticed when running `clang-tidy` on multiple files, the tool actually filtered out repeated messages and reported them once only. Running the whole charge of files, however, in a single core will be too long for a CI job.

I will probably either batch/bash or GNUmake/CMake something and handle redundant messages with either a parser of a lexer in some sensible way. Once done, Ill add this to a single CI job. See also #162.

**Comment by johnmcfarlane** [comment]
Might I make a suggestion: tackle this one check at a time.

1. Enable a check by removing the line with the `-` from _.clang-tidy.
2. Look through the errors that appear.
3. Decide if you agree with Clang-Tidy and if you don't, put back the `-` line and decide to deviate from that rule for good. (end)
4. Otherwise, fix anywhere where you can reasonably work around the problem (e.g. commenting out an unused function parameter) and `NOLINT` anything you're sure is a _false positive_.
5. Merge that change into the _main_ branch in isolation with the check re-enabled.
6. Goto 1

**Comment by ckormanyos** [comment]
> Might I make a suggestion: tackle this one check at a time.

Agreed @johnmcfarlane. That's kind of where I'm going on this. But the bulk of the _bigger' charges of syntax changes is basically done. Remaining are steady little improvements and process establishment.

> 1. Enable a check by removing the line with the - from _.clang-tidy.

Embarassingly enough, it broke down for me here. For some reason, either due to an old version or whatever or confusion on the command-line syntax, I could not get `clang-tidy` to read its configuration from `-file=whatever` --- nor from `.clang-tidy`.

I ended up running on the Ubuntu command bash with `*` checks activated and a handful of rules commented out. I sure would like to get these configuration details from `-file` if i could figure out how to do that.

As for the remaining 2-6, I see that as a process _after_ getting the bulk of these syntax changes in to main shortly.
