### ISSUE TITLE
Correct round to nearest regardless of FP flags

### ISSUE THREAD

**Issue by ckormanyos** [ckormanyos/wide-integer#148]
Ensure correct round to nearest regardless of FP flags. This was handled in preparations for Boost 1.79 and influences the test verification of wide-integer. Try to make wide-integer tests invariant regarding this change. it is not yet clear if wide-integer itself needs to be modified regarding rounding on cast-to-built-in-floating-point.

See also [multiprecision 401](https://github.com/boostorg/multiprecision/pull/401) and [multiprecision 360](https://github.com/boostorg/multiprecision/issues/360]

**Comment by johnmcfarlane** [comment]
Could changing rounding mode be considered a contract violation? I'm willing to hear otherwise, but it just sounds like a really bad idea to ever do that. Suddenly, a lot of otherwise-pure and deterministic code will start to behave differently due to global state. That's surely not desirable in a modern codebase. I'm not even sure if the FPU flag is guaranteed thread-safe. IIRC, on Windows 98 it was even global to the entire system!

**Comment by ckormanyos** [comment]
> changing rounding mode be considered a contract violation?

I'm not really informed enough to say. I think rounding is one of the trickier points on the big-int/float scene.

At the moment,  nobody is complaining in wide-integer. So my fisrt gut impression is not intending to actually change anything in wide-integer at the moment. Rather I'll intend to first see exactly how float-conversion is same or differs from Boost's and handle my tests via tolerances.

**Comment by ckormanyos** [comment]
I've removed the bug albel and reinterpreted this issue as a question.
