### ISSUE TITLE
(Previously '65536 bit integer') Infinite integer bit limit

### ISSUE THREAD

**Issue by HackerDaGreat57** [ckormanyos/wide-integer#154]
Just for future-proofing, I guess. The project that I'm making is designed to be expanded as much as possible, and I think that 64k for one number should be the limit.

Computer memory is increasing, and if Microsoft can randomly increase the amount of memory that Windows needs, so can we.

**Comment by ckormanyos** [comment]
> think that 64k for one number

I would like to leave the upper limit of compilation open-ended, if that's what you mean. One day far in the future, the integral type might provide the backend for other high-precision types needing much higher digit counts --- albeit a longer way in the future (if I ever get around to it).

If you mean simply the pre-defined aliases, then we only go up to 16k bits at the moment. Agreed that we can surely go up to 64k on these aliases.

TBD: Add pre-defined aliases for signed/unsigned `uint32768_t`, `uint65536_t`/`int32768_t`, `int65536_t`. Will do this ASAP.

**Comment by HackerDaGreat57** [comment]
😁 TYSM.

One day, far in the future when this project is **finished** (it's kinda small so that's probably gonna happen SOON) then maybe just keep on doubling the numbers just for fun? :D

**Comment by ckormanyos** [comment]
> Wait what? (u)int32768_t already exists.

The template class allows you to instantiate such types. The pre-defined alias for such a type exists.

If you would like 32k bits, simply do something like:

```
// The full template specialization of unsigned uint32768_t (using an allocator).
using uint32768_t = math::wide_integer::uintwide_t<32768U, std::uint32_t, std::allocator<void>, false>;
```

When using really large bit counts, use an allocator as shown above because otherwise stack storage might exceed the compiler's limits.

One practical limitatoin is the speed of multiplication and division. Since division uses classical Order(N^2) algorithms, it gets quite slow at large digit counts. Multiplication switches over to a Karatsuba scheme, so it is relatively fast. Several issues exist that trace higher-order multiplication/division schemes

**Comment by johnmcfarlane** [comment]
> then maybe just add that "open-ended" integer limit?

@HackerDaGreat57 is there some reason not to use the non-type template parameter? Hard-coding the width in the type name is mostly a C throwback. It's generally better to be specifying this as a parameter. What might persuade you?

**Comment by ckormanyos** [comment]
> Hard-coding the width in the type name is mostly a C throwback.

Correct. Recently I also learned that stylistically one might avoid using the `_t` suffix. This suffix is preferably reserved for the library. We had mention of this in another thread (that i can not find at the moment).

> ...is there some reason not to use the non-type template parameter?

This basically gets to the scope of the wide-integer library. Wide-integer is restricted to the bounded integer case and favorably uses type definitions having fixed widths.

> It would be an interesting experiment to see how many digits a modern computer's memory can hold.

Most clients of the wide-integer library are using fewer than 10k bits, in fact often 128, 256, 512 or so.

Indeed, however, other libraries (such as GMP) can be used to reach typical PC limits. Most digit hunters that I have worked with, limit regular desktop/PC calculations to a few billions of binary or decimal digits. It can be common to see programs calculating a billion digits of the mathematical constant pi. The GMP homepage has a program that handily calculates a billion digits of pi. This all makes sense because a typical desktop PC might have 8, 16 or 32 GB memory, leaving room 8without disk swapping) for a few instances of numbers with a few billion digits.

**Comment by ckormanyos** [comment]
Result of this issue:
- Add convenience types `(u)int32768_t` and `(u)int65536_t`.

**Comment by HackerDaGreat57** [comment]
@ckormanyos Thanks for the "fun math" tips. 

@johnmcfarlane I just thought that some strange program in the future may need more than 64k. I dunno, since Pi never ends, and some people may need more than 64k for breaking the record (that will eventually be increased a few trillion by then).

**Comment by ckormanyos** [comment]
>  happy with the new 64k type. Thanks a bunch

Please be aware that you can define your own instantiations of types exceeding 64k bits. Albeit, performance on mathematical operations multiplication and division will be slow, but such types can be used.

If you do this, consider using a line like shown above.

```
using local_uint131072_type = math::wide_integer::uintwide_t<131072, std::uint32_t, std::allocator<void>, false>;
```
