### ISSUE TITLE
Continuous testing

### ISSUE THREAD

**Issue by johnmcfarlane** [ckormanyos/wide-integer#46]
I was wondering though: have you thought of gating PRs on passing tests? (The practice is mentioned [here](https://en.wikipedia.org/wiki/Continuous_integration#Run_tests_in_CI)). To do this, I think you'd have to change the YML file [like this](https://github.com/johnmcfarlane/cnl/blob/main/.github/workflows/test.yml#L5) and make a change to the *master* branch in the project settings.

* The downside of this is that you cannot merge the code until all of the tests have passed, which slow down merges of error-free changes.
* The upside of this is that you cannot merge the code until all of the tests have passed, which blocks merges of failing changes.

Even if you don't block merges, it would still be helpful for contributors and reviewers to be able to see their PRs pass tests publicly. If you agree, I'd be happy to submit a PR.

**Comment by ckormanyos** [comment]
> have you thought of gating PRs on passing tests?

Agreed. This repository is actuially a good candidate for that. Recently I reduced CI time to less than 1 hour. So that is not extremely long. (Although I have this kind of thing running in some other domains, but not yet here).

I will initiate this quality gate at a time of my convenience shortly in the future.

**Comment by johnmcfarlane** [comment]
The CMake was already affected by a new source file, and I'm so used to getting feedback from CI so I made a branch for this just to help me with the constexpr PR. I'd be interested to know what you think.

Side note, while exploring the existing workflows, it occurred to me that you could probably speed up jobs by a small amount by providing a docker image with Boost already installed. Alternatively, might Boost install quicker using `apt get`?

Thanks

**Comment by ckormanyos** [comment]
>  CMake was already affected by a new source file, and I'm so used to getting feedback from CI so I made a branch for this just to help me with the constexpr PR. I'd be interested to know what you think.

It seems OK. Thanks.

> probably speed up jobs by a small amount by providing a docker image with Boost already installed. Alternatively, might Boost install quicker using `apt get`

What you end up _getting_ with `apt get` is a really old boost. I like to test on develop since I am also developing on Boost's develop. It's kind of like closing my world. We recently significantly reduced the Boost dependencies on Math and Multiprecision. In fact, math has standalone mode without needing rest of Boost. So the amount of Boost I'm cloning will be significantly reduced in the future. For the moment, I'd like to stick with Git clone submodules on-the-fly, but reduce the number of submods being cloned, as possible.

**Comment by ckormanyos** [comment]
See also #49

**Comment by johnmcfarlane** [comment]
#51 is a good example of how gating the merge on CI can be helpful. The option to prevent changes being merged prematurely are under: Settings -> Branches -> Branch protection rules -> master (edit) -> "Require status checks to pass before merging" and then check all the appropriate boxes there.

**Comment by ckormanyos** [comment]
> have you thought of gating PRs on passing tests?

Done, I believe. CI is running on the new, but a ways away from finished, _signed extension_ PR #54. Thank you @johnmcfarlane for the good suggestion and for your help on this matter.
